config/routes.rb
Rails.application.routes.draw do
  root "patients#index"
  resources :patients
  resources :households
  resources :syndromes
  resources :cases
  resources :locations
  
  post 'twilio/send_text_message' => 'twilio#send_text_message'
  
end

app/models/case.rb
# == Schema Information
#
# Table name: cases
#
#  id            :integer          not null, primary key
#  created_at    :datetime
#  updated_at    :datetime
#  urgency_level :integer
#  status        :string(255)
#  notes         :text
#  patient_id    :integer
#

class Case < ActiveRecord::Base
	belongs_to :patient
	belongs_to :clinician
  
	has_many :case_syndromes
  has_many :syndromes, :through => :case_syndromes 
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :set_case, only: [:update, :edit, :show]

  def index
    @cases = Case.all
  end

  def show
  end
  
  def edit
  end

  def update
    if @case.update(case_params)
          redirect_to @case, notice: "Case information was updated!"
      else
        render 'edit'
      end
  end 

  private 
  
  def set_case
    @case = Case.find params[:id]
  end

  def case_params 
    params.require(:case).permit(:status, :notes, :appointment)
  end
end

app/helpers/cases_helper.rb
module CasesHelper

    def status_list
    [
      ["OPEN", "OPEN"],
      ["CLOSED", "CLOSED"],
      ["IN PROGRESS", "IN PROGRESS"]
    ]
  end
end

app/views/cases/_calendar.html.erb
<div id='calendar'></div>

app/views/cases/_caselist.html.erb
<h3>Case Docket</h3>
<table class="table table-bordered" id="Case_Table">		
	<thead>
		<tr class="active" style="background-color: #CDFFE6">
			<td style="font-size: 14px"><strong>Case ID </strong></td>
			<td style="font-size: 14px"><strong>Status</strong></td>
			<td style="font-size: 14px"><strong>Issue Date</strong></td>
			<td style="font-size: 14px"><strong>Patient</strong></td>
			<td style="font-size: 14px"><strong>Household</strong></td>
			<td style="font-size: 14px"><strong>Syndromes List</strong></td>
			<td style="font-size: 14px"><strong>Urgency</strong></td>
			<td style="font-size: 14px"><strong>Appointment</strong></td>
			<td style="font-size: 14px"><strong>Contact Info</strong></td>
		</tr>
	</thead>

	<% @cases.each do |event| %>
	
	<tbody>
		<tr>
			<% link = event.id %>
			<td><%= link_to event.id, case_path(link)%></td>
			<td><%= event.status %></td> 
			<td><%= event.created_at %></td>
			<td><%= event.patient.first_name %></td> 
			<td><%= event.patient.household.name %></td>
			<% link = event.syndrome_ids %>
			<td><%= event.syndromes.map{|wl| link_to wl.name, syndrome_path(link)}.join(', ').html_safe %></td>
			<td><%= event.urgency_level %></td>
			<td><%= event.appointment %></td>
			<td><%= event.sender %></td> 
		</tr>
	<% end %>
	</tbody>
</table> 

app/views/cases/_form.html.erb
<%= simple_form_for(@case, html: {class: 'form-vertical'}) do |f| %>
  <%= f.input :status, collection: status_list  %>
  <%= f.input :notes %>
  <%= f.input :appointment %> 
  <%= f.button :submit %>
<% end %>

app/views/cases/edit.html.erb
<h1>Update Case Information</h1>
<%= render 'form' %>

app/views/cases/index.html.erb
<%= render 'caselist' %>

<%= render 'calendar' %>

app/views/cases/show.html.erb
<h2><em>Case Id <%=@case.id %></em></h2>
  <div class="panel-heading">
    <h3 class="panel-title"><%= @case.patient.first_name%> <%= @case.patient.last_name%></h3> 
  </div>

   <div class="panel-body">
        <div> 
          <img alt="User Pic" src="http://i.imgur.com/K7Um3.png" class="img-circle">
        </div>

        <br>
        
        <table class="table table-bordered">
            <tbody>
                <tr>
                  <td style="font-size: 14px"><strong>Household</strong></td>
                  <td style="font-size: 14px"><%=@case.patient.household.name%></td>
                </tr>

                <tr>
                  <td style="font-size: 14px"><strong>Time Reported</strong></td>
                  <td style="font-size: 14px"><%=@case.created_at.in_time_zone("Pacific Time (US & Canada)")%></td>
                </tr>
                <tr>
                  <td style="font-size: 14px"><strong>Reported Health Events</strong></td>
                  <% link = @case.syndrome_ids %>
                  <td style="font-size: 14px"><%= @case.syndromes.map{|wl| link_to wl.name, syndrome_path(link)}.join(', ').html_safe %></td>
                </tr>
                <tr>
                  <td style="font-size: 14px"><strong>Sent Images</strong></td>
                  <td><img alt="Diarrhea" src="http://www.clearfection.com/wp-content/uploads/2013/06/Diarrhea-150x150.jpg" class="img-rounded"> 
                    <img alt="Fever" src="http://longevitywellnessclinic.com/wp-content/uploads/2014/05/gbhead-e1401383447243-150x150.jpg" class="img-rounded">
                  </td>
                </tr>

                <tr>
                  <td style="font-size: 14px"><strong>Location</strong></td>
                  <td style="font-size: 14px"><em>Geographic Location<em></td>
                </tr>
                <tr>
                  <td style="font-size: 14px"><strong>Contact Info</strong></td>
                  <td style="font-size: 14px"><%= @case.sender %></td>
                </tr>
                <tr>
                  <td style="font-size: 14px"><strong>Urgency Level</strong></td>
                  <td style= "font-size: 14px"><%= @case.urgency_level %></td>
                </tr>
                <tr>
                  <td style="font-size: 14px"><strong>Notes</strong></td>
                  <td style="font-size: 12px"><%= @case.notes %></td>
                </tr>    
            </tbody>
      </table>