config/routes.rb
Rails.application.routes.draw do
  root "patients#index"
  resources :patients
  resources :households
  resources :syndromes
  resources :cases
  resources :locations
  
  post 'twilio/send_text_message' => 'twilio#send_text_message'
  
end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id           :integer          not null, primary key
#  created_at   :datetime
#  updated_at   :datetime
#  national_id  :string(255)
#  first_name   :string(255)
#  last_name    :string(255)
#  sex          :string(255)
#  age          :integer
#  language     :string(255)
#  medication   :text
#  conditions   :text
#  household_id :integer
#

class Patient < ActiveRecord::Base
	belongs_to :household
	has_many :cases

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	before_action :set_patient, only: [:update, :edit, :show]
	
	def index
		@patients = Patient.all
		if params[:q]
      		@patient = Patient.where("first_name LIKE ? OR household_id LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%").first
      		render 'show'
    	else
      		@patients = Patient.all
    	end
	end

	def show
	end

	def new
		@patient = Patient.new
	end

	def create
		@patient = Patient.new patient_params
    	if @patient.save
      		redirect_to @patient, notice: "Patient was saved."
    	else
      		render 'new'
    	end
	end

	def edit
	end

	def update
		if @patient.update(patient_params)
      		redirect_to @patient, notice: "Patient information was updated!"
    	else
     	 	render 'edit'
    	end
	end 

	private
	def set_patient
   		@patient = Patient.find params[:id]
	end

	def patient_params
		params.require(:patient).permit(:first_name, :last_name, :sex, :age, :language, :medication, :conditions, :household_id)
	end
end

app/helpers/patients_helper.rb
module PatientsHelper
  def language_list
    [
      ["English", 'English'],
      ["French", "French"],
      ["Spanish", "Spanish"]
    ]
  end

end

app/views/patients/_form.html.erb
<%= simple_form_for(@patient, html: {class: 'form-vertical'}) do |f| %>
  <%= f.input :national_id, label: 'National ID', placeholder: 'National ID' %>
  <%= f.input :first_name, label: 'First Name', placeholder: 'First Name' %>
  <%= f.input :last_name, label: 'Last Name', placeholder: 'Last Name' %>
  <%= f.input :sex, as: :radio_buttons, collection: ['Male', 'Female'] %> 
  <%= f.input :age, collection: 0..120  %>
  <%= f.input :language, collection: language_list  %>

  <%= f.association :household, :label_method => :name, :value_method => :id %>
  <%= f.input :medication %>
  <%= f.input :conditions, label: "Chronic Conditions" %>
  <%= f.button :submit %>
<% end %>




<!-- Setting Up Check Boxes- 
	Need to change conditions into an array- :conditions => []
f.input :conditions, as: :check_boxes,
    			collection: [
      				'Allergies',
      				'Crippled',
      				'Other']  -->


<!-- <form role="form">
	
	<div class="form-group">
		<label class="control-label" for="national_id"><strong>National ID</strong></label>
		<input type="string" class="form-control" id="NationalId" placeholder="Enter National Identification">
	</div>

	<div class="form-group">
		<label class="control-label" for="first_name"><strong>First Name</strong></label>
		<input type="string" class="form-control" id="FirstName" placeholder="First Name">
	</div>

	<div class="form-group">
		<label class="control-label" for="last_name"><strong>Last Name</strong></label>
		<input type="string" class="form-control" id="LastName" placeholder="Last Name">
	</div>

	<div class="form-group">
		<label class="control-label"><strong>Sex</strong></label>
		<div class="radio">
			<label>
			<input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
			Male
			</label>
		</div>
		<div class="radio">
			<label>
			<input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
			Female
			</label>
		</div>
	</div>

	<div class="form-group">
		<label class="control-label" for="Age"><strong>Age</strong></label>
		<input type="integer" class="form-control" id="Age">
	</div>

	<div class="form-group">
		<label class="control-label" for="Household"><strong>Household ID</strong></label>
		<input type="integer" class="form-control" id="Household_ID" >
	</div>

	<div class="form-group">
		<label class="control-label" for="Language"><strong>Language</strong></label>
		<input type="integer" class="form-control" id="Language" >
	</div>
 -->



<!-- <div class="form-group">
<label class="control-label" for="exampleInputPassword1">Password</label>
<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
<p class="help-block">Lorem ipsum dolor sit amet</p>
</div>
<div class="form-group">
<label class="control-label" for="exampleInputFile">File</label>
<input type="file" id="exampleInputFile">
<p class="help-block">Example block-level help text here.</p>
</div>
<div class="form-group">
<div class="checkbox">
<label>
<input type="checkbox"> Active
</label>
</div>
<p class="help-block">Lorem ipsum dolor sit amet</p>
</div>
<div class="form-group">
<label class="control-label">Choices</label>
<div class="checkbox">
<label>
<input type="checkbox" name="optionsRadios" id="optionsCheckbox1" value="option1" checked>
Option one is this and that&mdash;be sure to include why it's great
</label>
</div>
<div class="checkbox">
<label>
<input type="checkbox" name="optionsRadios" id="optionsCheckbox2" value="option2">
Option two can be something else and selecting it will deselect option one
</label>
</div>
</div>
<div class="form-group">
<label class="control-label">Sex</label>
<div class="radio">
<label>
<input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
Male
</label>
</div>
<div class="radio">
<label>
<input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
Female
</label>
</div>
<p class="help-block">Lorem ipsum dolor sit amet</p>
</div>
<button type="submit" class="btn btn-default">Create User</button> -->
</form>

app/views/patients/_patienttable.html.erb
<h3>Patient List</h3>
<table class="table table-bordered" id="Patient_Table">
	<thead>
		<tr style="background-color: #CDFFE6">
			<td style="font-size: 14px"><strong>Picture ID</strong></td>
			<td style="font-size: 14px"><strong>First Name</strong></td>
			<td style="font-size: 14px"><strong>Last Name</strong></td>
			<td style="font-size: 14px"><strong>Sex</strong></td>
			<td style="font-size: 14px"><strong>Age</strong></td>
			<td style="font-size: 14px"><strong>Household</strong></td>
			<td style="font-size: 14px"><strong>Language</strong></td>
			<td style="font-size: 14px"><strong>Medication</strong></td>
			<td style="font-size: 14px"><strong>Conditions</strong></td>
		</tr>
	</thead>

	<% @patients.each do |patient| %>

	<tbody>
		<tr>
			<td><%= 'Image Placeholder' %></td> 
			<td><%= patient.first_name %></td> 
			<td><%= patient.last_name %></td>
			<td><%= patient.sex %></td> 
			<td><%= patient.age %></td> 
			<td><%= patient.household.name %></td>
			<td><%= patient.language %></td>
			<td><%= patient.medication %></td>
			<td><%= patient.conditions %></td>
		</tr>
	<% end %>
	</tbody>
</table> 

app/views/patients/_pform.html.erb
<%= simple_form_for(@patient, html: {class: 'form-vertical'}) do |f| %>
  <%= f.input :national_id, label: 'National ID', placeholder: 'National ID' %>
  <%= f.input :first_name, label: 'First Name', placeholder: 'First Name' %>
  <%= f.input :last_name, label: 'Last Name', placeholder: 'Last Name' %>
  <%= f.input :sex, as: :radio_buttons, collection: ['Male', 'Female'] %> 
  <%= f.input :age, collection: 0..120  %>
  <%= f.association :household, :label_method => :name, :value_method => :id %>
  <%= f.input :language %>
  <%= f.input :medication %>
  <%= f.input :conditions %>
  <%= f.button :submit %>
<% end %>




<!-- Setting Up Check Boxes- 
	Need to change conditions into an array- :conditions => []
f.input :conditions, as: :check_boxes,
    			collection: [
      				'Allergies',
      				'Crippled',
      				'Other']  -->


<!-- <form role="form">
	
	<div class="form-group">
		<label class="control-label" for="national_id"><strong>National ID</strong></label>
		<input type="string" class="form-control" id="NationalId" placeholder="Enter National Identification">
	</div>

	<div class="form-group">
		<label class="control-label" for="first_name"><strong>First Name</strong></label>
		<input type="string" class="form-control" id="FirstName" placeholder="First Name">
	</div>

	<div class="form-group">
		<label class="control-label" for="last_name"><strong>Last Name</strong></label>
		<input type="string" class="form-control" id="LastName" placeholder="Last Name">
	</div>

	<div class="form-group">
		<label class="control-label"><strong>Sex</strong></label>
		<div class="radio">
			<label>
			<input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
			Male
			</label>
		</div>
		<div class="radio">
			<label>
			<input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
			Female
			</label>
		</div>
	</div>

	<div class="form-group">
		<label class="control-label" for="Age"><strong>Age</strong></label>
		<input type="integer" class="form-control" id="Age">
	</div>

	<div class="form-group">
		<label class="control-label" for="Household"><strong>Household ID</strong></label>
		<input type="integer" class="form-control" id="Household_ID" >
	</div>

	<div class="form-group">
		<label class="control-label" for="Language"><strong>Language</strong></label>
		<input type="integer" class="form-control" id="Language" >
	</div>
 -->



<!-- <div class="form-group">
<label class="control-label" for="exampleInputPassword1">Password</label>
<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
<p class="help-block">Lorem ipsum dolor sit amet</p>
</div>
<div class="form-group">
<label class="control-label" for="exampleInputFile">File</label>
<input type="file" id="exampleInputFile">
<p class="help-block">Example block-level help text here.</p>
</div>
<div class="form-group">
<div class="checkbox">
<label>
<input type="checkbox"> Active
</label>
</div>
<p class="help-block">Lorem ipsum dolor sit amet</p>
</div>
<div class="form-group">
<label class="control-label">Choices</label>
<div class="checkbox">
<label>
<input type="checkbox" name="optionsRadios" id="optionsCheckbox1" value="option1" checked>
Option one is this and that&mdash;be sure to include why it's great
</label>
</div>
<div class="checkbox">
<label>
<input type="checkbox" name="optionsRadios" id="optionsCheckbox2" value="option2">
Option two can be something else and selecting it will deselect option one
</label>
</div>
</div>
<div class="form-group">
<label class="control-label">Sex</label>
<div class="radio">
<label>
<input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
Male
</label>
</div>
<div class="radio">
<label>
<input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
Female
</label>
</div>
<p class="help-block">Lorem ipsum dolor sit amet</p>
</div>
<button type="submit" class="btn btn-default">Create User</button> -->
</form>

app/views/patients/edit.html.erb
<h1>Update Patient Information</h1>
<%= render 'form' %>

app/views/patients/index.html.erb
<h2>Patients</h2>

<%= form_tag patients_path, method: "GET" do %>
  <%= text_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
<% end %>

<%= render 'patienttable' %>

<%= button_to "Register Patient", new_patient_path, :id => 'patient', :class=> "btn btn-primary", :method => :get %>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

app/views/patients/new.html.erb
<h1>Patient Registration</h1>
<%= render 'form' %>

app/views/patients/show.html.erb
<h1>Patient List</h1>
<table class="table table-striped" id="Patient_Table">
<thead>
	<tr>
		<td style="font-size: 20px"><strong>Picture ID</strong></td>
		<td style="font-size: 20px"><strong>First Name</strong></td>
		<td style="font-size: 20px"><strong>Last Name</strong></td>
		<td style="font-size: 20px"><strong>Sex</strong></td>
		<td style="font-size: 20px"><strong>Age</strong></td>
		<td style="font-size: 20px"><strong>Household</strong></td>
		<td style="font-size: 20px"><strong>Language</strong></td>
		<td style="font-size: 20px"><strong>Medication</strong></td>
		<td style="font-size: 20px"><strong>Conditions</strong></td>
	</tr>
</thead>
<tbody>
	<tr>
		<td><%= 'Image Placeholder' %></td> 
		<td><%= @patient.first_name %></td> 
		<td><%= @patient.last_name %></td>
		<td><%= @patient.sex %></td> 
		<td><%= @patient.age %></td> 
		<td><%= link_to "House Hold", @patient.household %></td> 
		<td><%= @patient.language %></td>
		<td><%= @patient.medication %></td>
		<td><%= @patient.conditions %></td>
	</tr>
</tbody>
</table> 

<br> 

<%= link_to "Edit", edit_patient_path(@patient) %>