config/routes.rb
Rails.application.routes.draw do
  root "patients#index"
  resources :patients
  resources :households
  resources :syndromes
  resources :cases
  resources :locations
  
  post 'twilio/send_text_message' => 'twilio#send_text_message'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuickHealth</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">QuickHealth Advisor</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Household List", households_path%></li>
            <li><%= link_to "Patient List", patients_path %></li>
            <li><%= link_to "Case Docket", cases_path %></li>
            <li><%= link_to "Syndrome Identification", syndromes_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid">
	 <div class="row">
		<div class="span3">
			<h3>About Us</h3>
			Quick Health is a infectious disease surveillance system for rural clinics.
		</div>
		<div class="span9"><%= yield %></div>
	 </div>
  </div>
</body>

<footer>
  <div class="container">
    <div class="row">
        <div class="col-md-4">
            <ul class="nav nav-pills">
              <li class="active"><a href="#">About Us</a></li>
            </ul>
        </div>
    </div>
</footer>
</html>