config/routes.rb
Rails.application.routes.draw do
  root "patients#index"
  resources :patients
  resources :households
  resources :syndromes
  resources :cases
  resources :locations
  
  post 'twilio/send_text_message' => 'twilio#send_text_message'
  
end

app/models/household.rb
# == Schema Information
#
# Table name: households
#
#  id            :integer          not null, primary key
#  created_at    :datetime
#  updated_at    :datetime
#  name          :string(255)
#  mobile_number :string(255)
#  email         :string(255)
#

class Household < ActiveRecord::Base
  has_many :patients
  belongs_to :location

  validates :name, :mobile_number, presence: true 

  def self.search(search)
    Household.where("name LIKE ?", "%#{search}%").first
  end
end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
	before_action :set_household, only: [:update, :edit, :show]

  def index
    @households = Household.all
    if params[:search]
      @household = Household.search(params[:search])
      render 'show'
    else 
      @households = Household.all
    end
  end

	def show
	end

	def new
		@household = Household.new
	end

	def create
		@household = Household.new household_params
    	if @household.save
      		redirect_to @household, notice: "Household was saved."
    	else
      		render 'new'
    	end
	end

	def edit
	end

	def update
		if @household.update(household_params)
      		redirect_to @household, notice: "Household information was updated!"
    	else
     	 	render 'edit'
    	end
	end 

	private
	def set_household
   		@household = Household.find params[:id]
	end

	def household_params
		params.require(:household).permit(:name, :mobile_number)
	end
end

app/helpers/households_helper.rb
module HouseholdsHelper
end

app/views/households/_hform.html.erb
<%= simple_form_for(@household, html: {class: 'form-vertical'}) do |f| %>
  <%= f.input :name, label: 'Family Name', placeholder: 'Family Name' %>
  <%= f.input :mobile_number, label: 'Mobile Number', placeholder: '+1########' %>
  <%= f.button :submit %>
<% end %>

app/views/households/_householdtable.html.erb
<h3>Household List</h3>
<table class="table table-bordered" id="Household_Table">		
	<thead>
		<tr style="background-color: #CDFFE6">
			<td style="font-size: 20px"><strong>Name</strong></td>
			<td style="font-size: 20px"><strong>Mobile Number</strong></td>
			<td style="font-size: 20px"><strong>Household Members</strong></td>
			<td style="font-size: 20px"><strong>Language</strong></td>
		</tr>
	</thead>

	<% @households.each do |household| %>
	
	<tbody>
		<tr>
			<td><%= household.name %></td> 
			<td><%= household.mobile_number %></td>
			<% link = household.patient_ids %>
			<td><%= household.patients.map{|wl| link_to wl.first_name, patient_path(link)}.join(', ').html_safe %></td>
			<td> <%= household.patients.first.language.capitalize%> </td> 
		</tr>
	<% end %>
	</tbody>
</table> 

app/views/households/edit.html.erb
<h1>Update Household Information</h1>
<%= render 'hform' %>

app/views/households/index.html.erb
<h2>Households</h2>
<%= form_tag households_path, method: "GET" do %>
  		<%= text_field_tag :search, params[:search] %>
  		<%= submit_tag "Search" %>
<% end %>

<%= render 'householdtable' %>

<%= button_to "Add Household", new_household_path, :id => 'household', :class=> "btn btn-primary", :method => :get %>
  

app/views/households/new.html.erb
<h1>Household Registration</h1>
<%= render 'hform' %>

app/views/households/show.html.erb
<h1>Household List</h1>

<table class="table table-striped" id="Household_Table">
	<thead>
		<tr>
			<td style="font-size: 20px"><strong>Name</strong></td>
			<td style="font-size: 20px"><strong>Mobile Number</strong></td>
			<td style="font-size: 20px"><strong>Email Address</strong></td>
			<td style="font-size: 20px"><strong>Household Members</strong></td>
			<td style="font-size: 20px"><strong>Language</strong></td>
		</tr>
	</thead>
	
	<tbody>
		<tr>
			<td><%= @household.name %></td> 
			<td><%= @household.mobile_number %></td>
			<td><%= @household.email %></td> 
			<% link = @household.patient_ids %>
			<td><%= @household.patients.map{|wl| link_to wl.first_name, patient_path(link)}.join(', ').html_safe %></td>
			<td><%= 'Household Language' %></td>
		</tr>
	</tbody>
</table> 


<%= link_to "Edit", edit_household_path(@household) %>